version: '3.8'
services:
  backend:
    build:
      context: ./apps/backend
    container_name: mechbazar_backend
    ports:
      - 5005:5005
    environment:
      - PORT=5005
    volumes:
      - ./apps/backend/uploads:/app/uploads
    networks:
      - mechbazar_net
    env_file:
      - ./apps/backend/.env
    restart: unless-stopped
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
      args:
        VITE_API_URL: https://mechbazar.com/api
        VITE_SERVER_ORIGIN: https://mechbazar.com
    container_name: mechbazar_admin
    ports:
      - 3000:80
    networks:
      - mechbazar_net
    restart: unless-stopped
  vendor:
    build:
      context: .
      dockerfile: apps/vendor/Dockerfile
      args:
        VITE_API_URL: https://mechbazar.com/api
        VITE_SERVER_ORIGIN: https://mechbazar.com
    container_name: mechbazar_vendor
    ports:
      - 3001:80
    networks:
      - mechbazar_net
    restart: unless-stopped
  mobile:
    build:
      context: ./apps/mobile
      args:
        EXPO_PUBLIC_API_URL: https://mechbazar.com/api
    container_name: mechbazar_mobile
    ports:
      - 3002:80
    networks:
      - mechbazar_net
    restart: unless-stopped
networks:
  mechbazar_net: null
