/**
 * Makes a plain local `./gradlew assembleRelease` sign with the REAL release
 * keystore instead of the debug one.
 *
 * Why this exists
 * ---------------
 * `expo prebuild` writes the stock React Native template into
 * android/app/build.gradle, and that template deliberately ships a footgun:
 *
 *     buildTypes {
 *         release {
 *             // Caution! In production, you need to generate your own keystore file.
 *             signingConfig signingConfigs.debug
 *         }
 *     }
 *
 * There is only a `debug` signingConfig, and the release build type points at
 * it. So a local Gradle release build is signed with android/app/debug.keystore,
 * NOT with apps/rider/release.keystore (SHA-1 9B:E9:C6:ED:...).
 *
 * That is not a cosmetic problem, it breaks login. Firebase Phone Auth on
 * Android attests the app by package name + signing certificate:
 *   - the Firebase Android app `com.mechbazar.rider` has the release
 *     keystore's SHA-1/SHA-256 registered, and
 *   - the "Android key (auto created by Firebase)" GCP API key allowlists
 *     `com.mechbazar.rider` paired with that same SHA-1.
 * A debug-signed APK matches neither, so `accounts:sendVerificationCode` is
 * rejected at the API-key layer and every OTP attempt fails with
 * `auth/missing-client-identifier` -- the "Could not verify this device" error.
 * Google Maps and any future App Check/Play Integrity attestation fail for the
 * same reason. Nothing about it is diagnosable from the app's own logs, because
 * the rejection happens server-side before the SDK has anything to report.
 *
 * `eas build` (cloud or `--local`) does not need this: it injects credentials
 * from credentials.json / EAS servers through its own Gradle plumbing. This
 * plugin therefore stands down under EAS_BUILD so the two mechanisms cannot
 * fight over the same block -- it exists purely for the direct-Gradle path.
 *
 * build.gradle is regenerated by every prebuild, so this has to be a config
 * plugin rather than a hand edit -- editing android/app/build.gradle directly
 * would be silently reverted the next time anyone runs `expo prebuild --clean`.
 *
 * Credentials come from apps/rider/credentials.json, which is gitignored and
 * is already the source of truth for eas.json's `credentialsSource: "local"`.
 * If it is absent the template is left untouched and a warning is printed --
 * better an obviously debug-signed artifact than a build that dies on a missing
 * file in CI.
 */
const { withAppBuildGradle } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** EAS injects its own signing config; don't double-write the release block. */
const RUNNING_UNDER_EAS = process.env.EAS_BUILD === 'true';

/** @type {import('expo/config-plugins').ConfigPlugin} */
module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withAndroidReleaseSigning: expected a Groovy build.gradle, got ${cfg.modResults.language}.`
      );
    }

    if (RUNNING_UNDER_EAS) {
      console.log('[withAndroidReleaseSigning] EAS_BUILD detected -- leaving signing to EAS.');
      return cfg;
    }

    const credsPath = path.join(cfg.modRequest.projectRoot, 'credentials.json');
    if (!fs.existsSync(credsPath)) {
      console.warn(
        '[withAndroidReleaseSigning] credentials.json not found -- the release build will be ' +
          'DEBUG-SIGNED, which breaks Firebase Phone Auth (auth/missing-client-identifier) ' +
          'and Google Maps. See docs/LOCAL_BUILDS.md.'
      );
      return cfg;
    }

    const creds = JSON.parse(fs.readFileSync(credsPath, 'utf8'));
    const ks = creds?.android?.keystore;
    for (const field of ['keystorePath', 'keystorePassword', 'keyAlias', 'keyPassword']) {
      if (!ks?.[field]) {
        throw new Error(`withAndroidReleaseSigning: credentials.json is missing android.keystore.${field}`);
      }
    }

    // keystorePath is relative to apps/rider, but Gradle resolves relative
    // file() paths against android/app -- so hand Gradle an absolute path with
    // forward slashes (valid on Windows too, and avoids Groovy treating a
    // backslash as an escape).
    const keystoreAbs = path.resolve(cfg.modRequest.projectRoot, ks.keystorePath);
    if (!fs.existsSync(keystoreAbs)) {
      throw new Error(
        `withAndroidReleaseSigning: keystore ${ks.keystorePath} referenced by credentials.json does not exist.`
      );
    }
    const gradlePath = keystoreAbs.replace(/\\/g, '/');

    let contents = cfg.modResults.contents;

    // Idempotent: a second prebuild over an already-patched file (or a template
    // that gains its own release config upstream) must not stack a duplicate.
    if (contents.includes('signingConfigs.release')) {
      console.log('[withAndroidReleaseSigning] release signingConfig already present -- skipping.');
      return cfg;
    }

    const escape = (value) => String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'");

    const releaseSigningConfig = [
      '        release {',
      `            storeFile file('${gradlePath}')`,
      `            storePassword '${escape(ks.keystorePassword)}'`,
      `            keyAlias '${escape(ks.keyAlias)}'`,
      `            keyPassword '${escape(ks.keyPassword)}'`,
      '        }',
    ].join('\n');

    // 1. Add the release signingConfig alongside the template's debug one.
    const signingAnchor = '    signingConfigs {';
    if (!contents.includes(signingAnchor)) {
      throw new Error('withAndroidReleaseSigning: could not find the signingConfigs block.');
    }
    contents = contents.replace(signingAnchor, `${signingAnchor}\n${releaseSigningConfig}`);

    // 2. Repoint the release build type away from the debug config. Anchored on
    //    the template's exact comment + assignment so this fails loudly if the
    //    template ever changes, rather than silently leaving debug signing in
    //    place (the whole failure mode this plugin exists to prevent).
    const releaseAnchor =
      /(release \{\n)(\s*\/\/ Caution!.*\n\s*\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\n)?(\s*)signingConfig signingConfigs\.debug/;
    if (!releaseAnchor.test(contents)) {
      throw new Error(
        'withAndroidReleaseSigning: could not find `signingConfig signingConfigs.debug` inside the ' +
          'release build type. The Expo template changed -- update this plugin before shipping, ' +
          'or the APK will be debug-signed and OTP login will break.'
      );
    }
    contents = contents.replace(
      releaseAnchor,
      (_m, open, _comment, indent) => `${open}${indent}signingConfig signingConfigs.release`
    );

    console.log(
      `[withAndroidReleaseSigning] release build type now signs with ${ks.keystorePath} ` +
        `(alias ${ks.keyAlias}).`
    );

    cfg.modResults.contents = contents;
    return cfg;
  });
};
