/**
 * Keeps the Android NDK / C++ leg of the build inside a sane memory budget.
 *
 * Why this exists
 * ---------------
 * `react-native-reanimated` (and `react-native-worklets`) are the only
 * dependencies here that compile C++ from source. AGP builds them with CMake +
 * ninja, and ninja defaults to `<cpu count> + 2` concurrent `clang++`
 * processes. Each of those processes compiles reanimated's heavily-templated
 * CSS/animation translation units with `-O2 -g -flto=thin` and a precompiled
 * header, which costs roughly 1.5-2 GB of resident memory apiece.
 *
 * On a machine with many cores relative to its RAM (the dev box this was
 * diagnosed on has 12 logical cores and 7.3 GB), that fan-out exhausts the
 * Windows commit limit and clang dies with:
 *
 *     LLVM ERROR: out of memory
 *     Allocation failed
 *     clang++: error: clang frontend command failed due to signal
 *
 * ninja then reports `subcommand failed`, Gradle reports a failed
 * `:react-native-reanimated:buildCMakeRelWithDebInfo[...]` task, and EAS
 * collapses the whole thing into the useless "Gradle build failed with unknown
 * error". The compile is not broken -- it simply ran out of memory.
 *
 * `org.gradle.parallel` is the multiplier that matters: with it on, Gradle runs
 * the reanimated and worklets native builds (and, before `buildArchs` was
 * pinned in app.config.js, one build per ABI) at the same time, so the real
 * peak was several times ninja's own fan-out.
 *
 * gradle.properties is regenerated by `expo prebuild`, so this has to be a
 * config plugin rather than a hand edit -- EAS (local or cloud) prebuilds from
 * scratch and would otherwise drop it.
 *
 * Set EXPO_ANDROID_PARALLEL_BUILD=1 to opt back out on a machine with enough
 * RAM to feed every core.
 */
const { withGradleProperties } = require('expo/config-plugins');

const ALLOW_PARALLEL = process.env.EXPO_ANDROID_PARALLEL_BUILD === '1';

/** gradle.properties entries we own, applied in order. */
const PROPERTIES = [
  {
    key: 'org.gradle.parallel',
    value: String(ALLOW_PARALLEL),
    comment:
      'Serialized so the reanimated/worklets CMake builds cannot run at the same time -- ' +
      'concurrent ninja fan-out OOMs clang. See plugins/withAndroidBuildConcurrency.js.',
  },
  {
    key: 'org.gradle.workers.max',
    value: ALLOW_PARALLEL ? '8' : '4',
    comment:
      'Caps Kotlin/dex worker fan-out. This box has far more cores than it has GB of RAM, ' +
      'so the core count is the wrong default here.',
  },
];

/** @type {import('expo/config-plugins').ConfigPlugin} */
module.exports = function withAndroidBuildConcurrency(config) {
  return withGradleProperties(config, (cfg) => {
    for (const { key, value, comment } of PROPERTIES) {
      // expo prebuild already writes org.gradle.parallel=true from its template,
      // so replace in place rather than appending a second, losing definition.
      const existing = cfg.modResults.find(
        (item) => item.type === 'property' && item.key === key
      );

      if (existing) {
        existing.value = value;
        continue;
      }

      cfg.modResults.push({ type: 'comment', value: comment });
      cfg.modResults.push({ type: 'property', key, value });
    }

    return cfg;
  });
};
